language: go
go: 
 - "1.11.x"

os: osx

install: true

env:
  global:
    - GO111MODULE=on
    - CODECOV_TOKEN="994b5b99-a41a-4f56-9c75-0e5ae748db97"

addons:
  ssh_known_hosts:
  - github.com
  - ssh.github.com

script: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)